### ISSUE TITLE
Support Symbols-View

### ISSUE THREAD

**Issue by juh2** [superlou/fountain-atom#1]
It would be nice, if Command-R would show the scene outline.

**Comment by superlou** [comment]
That's a really cool idea.  I'm going to be on the road for a few days, but will look into it when I get back.  

How would you handle the case where multiple scenes have the same header?  Do you know of any text-like packages that implements symbols?  It doesn't look like the included markdown support registers any.

**Comment by juh2** [comment]
Github-Markdown and Pandoc-Markdown implements symbols so that Command-R gives me an outline of the headlines.

**Comment by superlou** [comment]
@juh2, do you have an additional package installed that generates the symbols?  Github Markdown doesn't provide any symbols on my install.

**Comment by superlou** [comment]
Until a symbols-view API is ready, the place to add symbols definitions is https://github.com/atom/symbols-view/blob/master/lib/.ctags.

**Comment by superlou** [comment]
The pull-request can be followed at https://github.com/atom/symbols-view/pull/113.

**Comment by juh2** [comment]
Yes. The Edit-Pane has to be the focus.

**Comment by superlou** [comment]
Pull-request is merged an in symbols-view 0.100.0.  Should be available in the next Atom update.

**Comment by superlou** [comment]
Available in Atom 1.0.2.
