### ISSUE TITLE
Character not centered.

### ISSUE THREAD

**Issue by PCycle2** [superlou/fountain-atom#11]
The character should be centered on a line of it's own with the dialogue centered under it. I glanced at the code and I didn't see a function for character next to dialogue or title. I'm guessing this got deleted on accident or something. I'd love to output to PDF but I know that's a whole different problem but I can't use this until that function works right. It's an absolute bedrock basic. Thanks for this package Superlou. I'd love to confer with you some more about the preview and hopefully someday the PDF output. 

Goodluck

**Comment by superlou** [comment]
@PCycle2 Can you add a screenshot of the issue?  Thanks!

**Comment by jrbostic** [comment]
@superlou Can this be closed since moving to afterwriting, or were you waiting until removal of the deprecated preview?

**Comment by superlou** [comment]
I'm willing to close it.  We never got a test case or screenshot, so we'll reopen or create a new ticket if it shows up.
