### ISSUE TITLE
Outline not working on Ubuntu Linux

### ISSUE THREAD

**Issue by jason-mehmel** [superlou/fountain-atom#12]
I've just installed Atom and Fountain-Atom on Ubuntu 16.10 on an Asus Zenbook. The preview works fine, but the outline has no response from the keyboard.

To confirm, it's ctrl-alt-o with 'o' as in 'opera'?

**Comment by superlou** [comment]
Per https://github.com/superlou/fountain-atom/blob/master/keymaps/fountain.cson, it should be.  I will try it tonight on Linux Mint (Ubuntu-derived).  Does running the Fountain ToggleOutlineView command work? Try ctrl+shift+p to get the command palette.

**Comment by superlou** [comment]
Per https://github.com/superlou/fountain-atom/blob/master/keymaps/fountain.cson, it should be.  I will try it tonight on Linux Mint (Ubuntu-derived).  Does running the Fontain ToggleOutlineView command work? Try ctrl+shift+p to get the command palette.

**Comment by jason-mehmel** [comment]
The command works! Just not the shortcut keys. And the preview shortcut does work.

**Comment by superlou** [comment]
If you start the key binding resolver (ctrl-.), is ctrl-alt-o is being overridden by another plugin?

**Comment by jason-mehmel** [comment]
It's weird; when I try that combo nothing comes up in the resolver. I'm not
sure if there's a shortcut in the window manager or something that isn't
active but is masking it or taking precedence against Atom?

~Jason
jmehmel@gmail.com | www.jasonmehmel.com

**Comment by superlou** [comment]
That's really odd.  Window manager or something's a pretty likely candidate.  Any chance you have [ClipIt](https://askubuntu.com/questions/592654/ctrlalto-organize-imports-not-working-on-intellij-idea) installed?  If you try [remapping it to another key](https://discuss.atom.io/t/how-do-i-create-keyboard-shortcuts/35861/3) does that work?

**Comment by jason-mehmel** [comment]
That worked! I mapped it to ctrl-alt-u and that seems to work fine. Now to
figure out which other app is owning that...

~Jason
jmehmel@gmail.com | www.jasonmehmel.com

**Comment by superlou** [comment]
Happy to help!
