### ISSUE TITLE
(CONT'D) breaks dialogue syntax highlighting

### ISSUE THREAD

**Issue by OgierM** [superlou/fountain-atom#16]
![image](https://user-images.githubusercontent.com/29630575/28333268-ae5a7f4e-6bf7-11e7-9361-48b75dc873e6.png)

**Comment by superlou** [comment]
Confirmed.  It seems to work fine in the preview window.

**Comment by superlou** [comment]
Should be fixed in 0.5.6.

**Comment by OgierM** [comment]
The character name is now highlighted, but the dialogue isn't green yet

**Comment by superlou** [comment]
Try 0.5.7.  Thanks for keeping me honest. :)  If you are an Atom grammar guru, I suspect that [these lines](https://github.com/superlou/fountain-atom/blob/master/grammars/fountain.cson#L58-L61) are redundant to line 65.  I've just been keeping them in sync (and occasionally forgetting to).

**Comment by OgierM** [comment]
@superlou I'd really like to help, but I just see a super long regex and have no clue what I want to do with it

**Comment by superlou** [comment]
No problem.  Did 0.5.7 fix the dialogue?

**Comment by OgierM** [comment]
![image](https://user-images.githubusercontent.com/29630575/28348443-59e9ba24-6c3d-11e7-87ed-37235a5d7844.png)
