### ISSUE TITLE
Why are 3 fountain screenplays being delivered with the package?

### ISSUE THREAD

**Issue by OgierM** [superlou/fountain-atom#18]
I found:
- [Big Fish](https://github.com/superlou/fountain-atom/blob/master/big_fish.fountain)
- [The Last Birthday Card](https://github.com/superlou/fountain-atom/blob/master/The%20Last%20Birthday%20Card.fountain)
- [The Last Birthday Card](https://github.com/superlou/fountain-atom/blob/master/lib/The%20Last%20Birthday%20Card.fountain) (again)

are they important?

**Comment by morekitsch** [comment]
Probably a mistake on.my part. The last birthday card has some nested
scenes that are needed to test nesting, but you shouldn't need two of them.

**Comment by superlou** [comment]
Very possibly my fault as well. :)  They should probably be moved into tests, even if they're aren't doing any automated testing (which is a thing we should do).

**Comment by jrbostic** [comment]
I removed these files.  I just figured... if you need a new file for a new test, then you would add it at that time.  Of course, I won't be offended if you reject my PR in favor of migrating the files to spec folder.

**Comment by superlou** [comment]
Can we hold onto one copy of big_fish.fountain in the spec folder?  This is partly laziness, but while the coverage is somewhat spotty, it makes testing some functionality very convenient.  The other two can be deleted.

**Comment by jrbostic** [comment]
Yea, I'm not tripping.  I'll update this later tonight.

**Comment by morekitsch** [comment]
BIg fish doesn't implement Acts or Section levels. For testing Birthday is
best. Big fish is very straight forward in terms of structure, Birthday is
not.

But we don't need any of them unless we are doing some tests.

**Comment by jrbostic** [comment]
It's all good.  I'll just shove both back in there.  And we will need birthday sooner or later, for testing nested scene dragging.

**Comment by IBPX** [comment]
As far as I know, Big Fish is copyrighted by Columbia Pictures, all rights reserved. A copy is distributed on Fountain.io, because John August (the author) is part of the Fountain project. Is there any sort of license that actually permits redistribution? If not, this project may be violating Columbia/John's copyright by including it.

**Comment by jrbostic** [comment]
The file's removal from inadvertent redistribution is pending.  Please see PR #30.  @superlou @morekitsch

**Comment by superlou** [comment]
I had initially thought both Big Fish was redistributable since it's included in the tests of [the example implementation](https://github.com/nyousefi/Fountain/blob/master/FountainTests/Big%20Fish.fountain).  Is it a similar situation with The Last Birthday Card?  If we can't be sure, let's remove both of them.  @jrbostic, sorry about the PR churn.

**Comment by jrbostic** [comment]
I honestly don't think the creators of fountain will be trying to shut down an open source package for using the sample fountain texts they provided for writing tests.  This plugin is one of the only truly free options that supports their own work (it adds value and there's no profit being made).  Nonetheless, I've removed The Last Birthday Card sample.  We will just need to generate a new example with a similar structure when we get to the outline drag/drop upgrades.  @superlou please see updated pr

**Comment by superlou** [comment]
I agree it's unlikely Fountain's creators would take issue.  Unfortunately, I think it's safest to remove them for now.  Closing this with the merge of #30.  We'll just have to get someone to offer a screenplay to use for tests.

```
INT. - HACKER'S APARTMENT

Light rays spill in, suspended on the dust churned by the slow rotation of an industrial fan.  The room is tight: reclaimed cinder block entombs the chipped metal desk.  The edges of JRBOSTIC's flannel hoodie glow green in the CRT's oppressive light.

JRBOSTIC
One.  Last.  P.  R.  I'll show them.  I'll show them all.

...
```

**Comment by jrbostic** [comment]
Haha, yes!  A screenplay based on the atom-fountain GitHub issues may be the most entertaining to test...
