### ISSUE TITLE
Outline view from Sections/Synopsis/notes

### ISSUE THREAD

**Issue by morekitsch** [superlou/fountain-atom#2]
Hi superlou,

Thank so much for writing this fountain package it's great to have it in Atom.

I have a feature request for you: an outline view based upon section/synopsis/notes entries in fountain (#section one, ## section two, =synopsis, [[note under symposis]] [[second note]], etc).

This page gives a good example:
http://slugline.co/blog/outlinefromfountain

I don't expect a rendered outline like in the example (right side of the image in the example), more of a working outline navigator (left side of the image in the example) similar to the work you have done with the scene list navigator except containing sections, synopsis, and notes maybe).

I'm trying to write my own version/branch, but I'll be honest I'm not sure I fully understand how things are rendered in Atom(spacepen is depreciated, or it isn't.. I cant tell!! I've also written a few loops that froze Atom :p) I'll keep taking stabs at it, but you'd probably do a better job so I'm tossing this up to you if you feel inclined.  A foldable combo of sections+synopsis+notes+scenelists would be amazing (using a tree-view navigator) anyway I'll leave considerations and methods to you if you get inclined to pursue this.

If you really wanted to get crazy you'd look into rearranging order by dragging sections up/down in the tree-view and reflect in the source as block moves, thereby turning the view into a sortable 'index card' like system and making all the other fountain implementations jealous.

**Comment by superlou** [comment]
Thanks for the idea!  That outline looks pretty slick.  I was hoping to start integrating something like that into the Atom package, but the parsing engine being used is pretty limited with respect to linking the extracted sections to the actual text.  Being able to rearrange sections by dragging was on the list of goals, but this limitation made it difficult.  As you noticed, Spacepen is deprecated, and I was hoping to switch to whatever's the best practice templating system before I make too many changes.  I don't know if I'm going to be able to look into it in the near term, but I'd be happy to apply pull requests.  This isn't abandoned, but might be a little bit before I can get back to it.

**Comment by morekitsch** [comment]
For me the outline is the best use of fountain. Portability is nice, but being able to sketch and outline within the text without using some hokey notes system is a feature that sets it above standard screenplay editors.

No rush on development. I'm still figuring things out. so there is a chance you'll still beat me to implementation.

I spent a good deal of last night trying to make heads of what to use for a framework. The going consensus was vue.js or etch, but there are a good number of people that want to use custom elements in raw js/coffeescript. Nothing seems firm.

I did notice the block level limitations of the editor. Seems like they should have an API to abstract and catalog things so you can make manipulations on the text without needing to scan through it all the time.

I'll see if I can make some production ready code. If nothing else I'm learning somethings and your start has been valuable for that.

**Comment by morekitsch** [comment]
I essentially created all of these features except the reordering (which is a bit over kill since it's a text format).

Could I get write access to get my fork as a branch to yours?

**Comment by superlou** [comment]
Awesome!  Added you as a collaborator.  If you create a branch, I'll try it out on my end.

**Comment by morekitsch** [comment]
Great, Thanks!

**Comment by morekitsch** [comment]
Created the branch. There are just some modifications to /lib/fountain.coffee. I added a /lib/fountain-outline-view.coffee file and added a few styles to the /styles/style.css file.  The Last Birthday.fountain is added to /lib as a test. It's actually from the creator of fountain.

I really wish there was a way to easily resize panels(I see panes, but no panels got a resize feaure -- not that I can make heads or tails of actually implementing). I'd also prefer this on the left side with a  macro to set the file view to auto hide or something. No idea how I'd do that. I wish they would update the docs for stuff like that.

**Comment by superlou** [comment]
@morekitsch, that looks really slick.  There're other packages doing resizable panes, but I think they're manually watching for mouseclick events to perform dragging.  I'm really hoping that Atom builds the pane dragging into core sometime soon.  Would really fix some consistency issues between packages.

Given the huge overlap in functionality between the scene list and the outline view, would you want to merge the two tools together, especially as my quick scene list parser seems to incorrectly identify some action in The Last Birthday as scenes?  I think you're outline view can replace the scene list functionality just by using Atom toggle boxes in the upper right of your pane to toggle listing of scenes and sections.  That way someone can get your hide scenes functionality by turning off scenes, or getting a traditional scene list by turning of sections, or get the full outline by leaving both on.

**Comment by morekitsch** [comment]
Thanks! I had fun making it. I'd be happy to merge. Anyway it would give
ctrl+alt+o to the outline.

I tried to steal the resize pane from the tree view, but decided it was
becoming a bit too crufty and jumbled together.

**Comment by morekitsch** [comment]
Hi,

I was I saw that you have a few updates, but the view I made isn't in them. We're you expecting some more work from me? Happy to do it I just thought the integration stuff fell under your auspices. The code I have in my branch just needs the ctrl-alt-o call changed to point to my ctrl-alt-h call then the -h one deleted. Agin I'm happy to do it I just thought it would be better for you since it's your codebase.

**Comment by superlou** [comment]
I actually thought you were working on merging your new outline view with the scene view.  Sorry!  If you update the branch from the master with the integration, it can be pulled in so at least you have the outlining.  I haven't had the time to do much other than really minimal tweaks like the one that just got released.

**Comment by morekitsch** [comment]
Updated and made a pull request. This will make Outline View replace Scenelist (since they do the same thing). Should be painless.

I should have made a comment sooner we could have done this three months ago.  Thanks!

**Comment by superlou** [comment]
Looks good.  Can you update the pull request with the latest grammar which implements some of the emphasis markdown?

**Comment by morekitsch** [comment]
Sure. I never touched the grammar so I figure it would just merge past it.  If that is the case I'll Just redo my branch with what I have local instead of just changing the few files I know of. Just a minute. This will be based on 0.4

**Comment by superlou** [comment]
Thanks.  I've gotten a bit skittish about how APM updates, since last time I went up two minor versions unintentionally.

**Comment by morekitsch** [comment]
That should do it. local version has *italics*, _underline_, and **bold** working. Bold is sort of reddish, underline and italics look the same. that's correct if I recall.

**Comment by morekitsch** [comment]
I can see why I deleted a full section of yours and it said it could auto update I thought that was weird. I should read up on this more. This is actually my first time doing much with a shared repo. hence not knowing what I was allowed to do.

**Comment by superlou** [comment]
Same here.  I think I merged in the pull request.  I had to do it manually because I really ticked off APM when I tried to undo the double minor version bump.  Version 0.5.0 should be released with your outline.  Thanks for the great contribution!

**Comment by superlou** [comment]
@morekitsch Just checking to make sure this is working as you expect.  If so, I'll close this issue.  Thanks!

**Comment by superlou** [comment]
Closing unless there's further feedback.

**Comment by morekitsch** [comment]
Nope thanks!

**Comment by jimyiapanis** [comment]
Has this been implemented? I try to "Toggle Outline View" and nothing happens. How can I turn on outline view?

**Comment by superlou** [comment]
@jimyiapanis If you press ctrl+shit+p, and start typing outline view, one of the autocomplete options should be the fountain outline view.  Can you check what version of this plugin you have installed?
