### ISSUE TITLE
Proper Serialization of Outline View

### ISSUE THREAD

**Issue by jrbostic** [superlou/fountain-atom#22]
Outline view isn't serializing/deserializing, so the pane disappears on refresh.

**Comment by superlou** [comment]
I started fixing this.  It's a little bit of a mess given how outline view is structured, so I've made a quick patch to at least get rid of the console errors for now.  However, the outline view isn't really serializing it's own state, so the status of the show scenes checkbox gets lost.  It would be nice to address this during #20.

**Comment by jrbostic** [comment]
I agree that it should be done.  And I'd be happy to take the ticket for it.  To be honest though, I guess I'm a little hesitant about adding more work to that branch.  My personal inclination is to get that piece in and then be able to work on smaller, preexisting issues independently.  Also, I don't know how much work the fix would be.  However, if that's a precondition of getting #20 in, then I'll do it.

**Comment by superlou** [comment]
If we're worried about it being a blocker for #20, I'm fine addressing it separately/later now that the plugin isn't throwing errors.

**Comment by jrbostic** [comment]
Yea, that's pretty much it for me.  I don't even mind doing it as my very next task.  It wasn't until the end there where I realized exactly what the issue was.  And I have other improvement tickets in mind if/when these are accepted... I just don't want to be presumptive.

**Comment by jrbostic** [comment]
@superlou looked like you may have fixed this.  Is this resolved now?

**Comment by superlou** [comment]
I sort of brute forced removed the path that generated errors due to serialization/deserialization simply not existing.  If we aren't seeing any practical issues at this point, it might be worth closing this issue and opening new ones with specific problems as they're discovered.

**Comment by jrbostic** [comment]
Well it worked for me both with and without preview open.  However, viewing only a single file in editor.  I'm not sure that the outline currently targets an editor instance by id, so I'm unclear on how it would deserialize with multiple editor panes open.  As long as atom manages focus on editor panes automatically it should appear in same state.

**Comment by jrbostic** [comment]
Not even sure that's a significant issue anyway.

**Comment by superlou** [comment]
Agreed.  Really, I think the outline panel should be moved to the more full featured [dock API](https://atom.io/docs/api/v1.20.1/Dock).  I'll close this issue.
