### ISSUE TITLE
Menu Toggle Doesn't Work

### ISSUE THREAD

**Issue by jrbostic** [superlou/fountain-atom#24]
I'm not sure if the menu Toggle doesn't work or what's up... But I can't get it to do anything obvious.  Confused me when I first installed the package.  IMO, it should be clarified and/or fixed, or removed.  It diminishes user confidence in the package.  As a user, I'd like to see two or three items there that initialize the fountain panels.

**Comment by superlou** [comment]
I think it was an oversight from a long time ago.  I updated the menu items and removed the context-menu items.
