### ISSUE TITLE
Special characters are currently unsupported in syntax highlighting

### ISSUE THREAD

**Issue by 4of92000** [superlou/fountain-atom#34]
The [syntax](https://fountain.io/syntax) for Fountain includes special characters to force a syntactic meaning to a line (so . at the beginning of a line forces a scene header, @ forces a character name, ! forces a line to be normal action, etc).

If you could implement those in the highlighting, that would be great.

Thanks.

**Comment by 4of92000** [comment]
sorry, touchscreen glitched out

**Comment by captaindooley** [comment]
Just wanted to chime in to request support for this... Some of these seem to work. I know . forces a heading line but @ does not work to force a character line. That said, the PDF preview does seem to render it correctly, but it's not color coded correctly in the main screen.

**Comment by superlou** [comment]
Are there other special characters that you noticed aren't working in the syntax highlighting, or just character names?

**Comment by captaindooley** [comment]
A quick test of syntax shows the following to me:

Forced transition, action, scene heading, centered text elements all work correctly.

Character doesn’t have syntax highlighting but works in the pdf output.

Dual dialog (^) has correct syntax highlighting but formats weird (overlapping text) in the PDF output.

Lyrics (~) and sections (#) don’t appear to have syntax highlighting, but appear correct in the pdf output (lyrics are italics, sections don’t show up)

Kevin Dooley
469.446.2539
@KevinBDooley
________________________________

**Comment by superlou** [comment]
I'll work on this through #39 (anyone else is also welcome to address these).

1. Forced character highlighting via @ should work.
2. Lyrics should be straightforward, and putting them in italics seems sensible since that mirrors the output format.
3. I'm not sure how to approach section formatting.  I'm open to ideas.

The dual dialogue formatting is likely a thing with Afterwriting, though I thought I had seen a working example of that.  Would you mind opening a new issue for that one, providing a short test script that causes the issue and adding a screenshot?

**Comment by jrbostic** [comment]
Afterwriting does have some configuration support, if I remember.  I was actually thinking about how we might provide some kind of old school config override (like how bash does it).  A configurable UI certainly seems like the appropriate end goal, but we could also quickly drop in a scanning mechanism that could discover custom configuration in the meantime... Just an idea.

**Comment by captaindooley** [comment]
I opened ticket #40 concerning the dual dialog. It appears that it's a spacing issue with the second dialog on the right.

**Comment by superlou** [comment]
A PR with proposed solutions is ready for review in #39.
