### ISSUE TITLE
Unwanted Text in PDF Preview/Output

### ISSUE THREAD

**Issue by captaindooley** [superlou/fountain-atom#38]
I just went to use the PDF preview function and noticed that on the first page of content, after the title page, it inserted the words "Format: Screenplay" at the top of the page.

The text immediate proceeding it was my contact info of the title page:

```
Contact:
  kxxx.dxxx@gmail.com
  4XX.XXX.2XXX
```

The text immediately following it was a forced transition:

`>FADE IN:`

A screenshot of the text is attached.

![bad text](https://user-images.githubusercontent.com/29738494/32418606-d8c6ffaa-c232-11e7-95cb-9b2eba04b0d2.png)

**Comment by captaindooley** [comment]
Er... umm... Well, nevermind. I went back to the document and somehow that line was actually added to the very top of the file, above the title page info and then it wound up on the next page in the preview. Something must have parsed the file at some point and appended that to the top of it... but I can't imagine what that would be.

**Comment by superlou** [comment]
Interesting.  I don't think we're doing anything that could add that string.  The text "Format" never appears in the Fountain-Atom source.  Maybe some edge case in the syntax highlighter?  I'll keep my eyes open for this.

Any chance you exported your script from another program which might have added it?

**Comment by captaindooley** [comment]
I have opened it/exported it through a couple different tools just playing with workflow. It appears one of those changed the file. We can close this out, just wanted to see if anyone else had seen it. Thanks for your time!

Kevin Dooley
469.446.2539
@KevinBDooley
________________________________

**Comment by superlou** [comment]
No problem.  Happy it's an easy resolution.
