### ISSUE TITLE
Dual Dialog Rendering

### ISSUE THREAD

**Issue by captaindooley** [superlou/fountain-atom#40]
Upon further inspection, Dual Dialog appears normally on the PDF output unless the second/right piece of dialog is longer than the first/left... then the second/right dialog overlaps the element below. I found this when using a parenthetical. It appears that the length of the dialog on the right is not factored into the spacing on the PDF output. See the image below for examples.

```
JILL
Jill Line 1

JACK ^
(tipping his hat politely)
Jack Line 1

JILL
Jill Line 2

JACK ^
Jack Line 2

JILL
Jill Line 3

JACK ^
(tipping his hat)
Jack Line 3

JILL
Jill Line 4

JACK ^
Jack Line 4

JILL
(tipping his hat politely)
Jill Line 5

JACK ^
Jack Line 5

JILL
Jill Line 6

JACK ^
Jack Line 6

JILL
(tipping his hat)
Jill Line 7

JACK ^
Jack Line 7

JILL
Jill Line 8

JACK ^
Jack Line 8
```

![screen shot 2017-11-06 at 21 05 15](https://user-images.githubusercontent.com/29738494/32475221-4dd00cc0-c336-11e7-8ffe-c6f7265ff763.png)

**Comment by jrbostic** [comment]
The only thing we could do here is default the config to not support this parallel output.  It's a single Boolean configuration.   Beyond that, I think it's an issue for the Afterwriting project...

**Comment by captaindooley** [comment]
Copy. Assuming I have no idea what the Afterwriting project is... any chance you could point me their way so I could bring this to their attention?

**Comment by superlou** [comment]
@captaindooley See this github project: https://github.com/ifrost/afterwriting-labs.  As of recently, it does all of the preview and export for the scripts.

**Comment by captaindooley** [comment]
Cool. I filed a ticket on that project. Since this is not directly addressable here, I'll close this out.
