### ISSUE TITLE
Need to apm publish patch

### ISSUE THREAD

**Issue by superlou** [superlou/fountain-atom#41]
Something has gotten fouled up with my git or apm or a combination (again).  It refuses to use my stored token, and 2-factor auth is preventing me from publishing.  @morekitsch, can you check out the trunk, and `apm publish patch`?

**Comment by jrbostic** [comment]
Could you try this:  https://github.com/atom/apm/issues/135  

Sounds like a similar problem?

**Comment by superlou** [comment]
Yeah, tried that one.  It seems like the same symptoms, but `apm login` works and `publish` doesn't.  The really frustrating part is that this used to work fine with occasionally issues.  This is the first time it's just stopped.

**Comment by jrbostic** [comment]
How about... https://github.com/atom/apm/issues/315

The 4th or 5th entry down the thread starts to talk about the behavior you described...  Although, that seems too easy.  I'm guessing you've been at this for a while, so I'm probably not going to have some silver bullet... but every once in a while, the simple thing is the missing ingredient.  :)

I also saw one issue talking about an expired OAuth key stored by APM...

Idk... that was my best attempt based on your APM issue.  Is there any other output after the publish fail?  Or is it just silent?

**Comment by superlou** [comment]
Fixed by https://discuss.atom.io/t/apm-not-recognizing-login-unable-to-publish/50526.  Not sure what changed, but creating a personal access token worked.
