### ISSUE TITLE
Feature RQ: Mark [[comments]] as such in syntax highlighting?

### ISSUE THREAD

**Issue by 4of92000** [superlou/fountain-atom#46]
Could you mark Fountain comments (double brackets) as such in syntax highlighting so I can find them faster? Thanks.

**Comment by superlou** [comment]
That's very reasonable, though I'm not sure I'll be able to look at it for a few days, sorry.

**Comment by superlou** [comment]
This should be fixed in 0.7.1.  Let me know if you run into any issues.
