### ISSUE TITLE
Atom switches to pdf preview tab every time fountain file is saved

### ISSUE THREAD

**Issue by double-u-a** [superlou/fountain-atom#47]
If someone likes to habitually save often but keep editing the script this can break up the flow, especially since the generation of the pdf takes a second or so everytime.

I would propose that automatic generation should perhaps be a user config option for those crazy kids that save infrequently. Alternatively the pdf preview could be generated but prevent Atom from switching focus to it somehow.

**Comment by jrbostic** [comment]
I think this is a good idea.  In fact, I'd like to see both parts implemented.  A bookean settings option like "preview take focus on save" and then, if not checked, prevent the pane from taking focus if it's already open.  I'd also be curious to see how the pdf-view package's own settings would interact with this (it has an atom setting regarding whether to refresh on file changes internally).  Maybe get the best of both worlds.  

However, there was some historical behavior in the fountain package for this... I think that's what current behavior was based on... I just can't remember which thread we discussed it in or what the options were.

**Comment by jrbostic** [comment]
*boolean

**Comment by double-u-a** [comment]
A background refresh would be really good. I've also actually noticed this behaviour only happens after you first manually generate a preview with the keybinding, if you never preview in your session you can save the file without generating a pdf.

I looked quickly at the code (not proficient in JS or CS at all) and I think might be [this line where it just runs the pdf preview on save automatically](https://github.com/superlou/fountain-atom/blob/d99b412ff7e5698b60e5ad8fc31a62f8f431ad18/lib/fountain.coffee#L212).

Great work on this to all involved, its very useful to have!

**Comment by jrbostic** [comment]
That's right.  The event is associated with having the actual preview state activated.   It was intentional.  But given this issue report, I'm wondering if we can defer that refresh to pdf-view package.  It also begs the question of if we need an indicator when you have preview turned on... I hadn't actually considered that the preview is a latent state and end users have no obvious way to determine that it's toggled on or off.

**Comment by jrbostic** [comment]
One potential issue for deferring to pdf-view package could be that the file is totally replaced, so it may lose reference... I'll run some tests on that.

**Comment by jrbostic** [comment]
At the very least a fountain config would be relatively easy to add.  And an indicator would have to be a decision weighed in on by @superlou.  Maybe if there's a config, we could fire preview generation function once, when config is set to not auto refresh, and activate the state otherwise.  

Or just get rid of auto refresh all together... That would be really easy.

**Comment by jrbostic** [comment]
Gosh, I guess I was wrong about this being stateful.  Instead, the line @double-u-a references is actually registering the preview generation function with atom... And I'm not sure there's any point where it gets deregistered!  Is this a legit bug that's causing the preview to pop back up even after closing its pane?

**Comment by jrbostic** [comment]
Confirmed.  Intertwined with the ux issue is a real bug.  I will provide a general fix ASAP.  Should be small changes.  Will update when I get it hammered out.

**Comment by jrbostic** [comment]
So, some good news, I think.  Discovered that pdf-view is automatically picking up the pdf changes that are created via fountain package.  I also figured out how to keep new pdfs from automatically taking focus when rendered.  That could easily be a package setting if there were some workflow where someone wants it to always take focus.  Auto-generating on save could also be a package setting.

I haven't figure out:
 1. how to take focus with the pdf on _only the first render_ (although, I have an idea)
 2. what to do about indicating that preview is toggled to the "on state" (if we keep auto-generation on save)

Questions to answer:
 1. do we want to keep the pdf automatic generation on save?
 2. if so, ctrl+shift+alt+m is more of a toggle than a generation hotkey?
 3. is it worth it to maintain this invisible "stateful" behavior?

**Comment by jrbostic** [comment]
@superlou @double-u-a See PR #48 for "fix".  Tried to salvage the behavior... but I'm not convinced it's worth the effort.  Not sure if this is an issue close to anyone's heart.  Patch will at least tentatively solve the actual bug.  Happy holidays!

**Comment by double-u-a** [comment]
@jrbostic that's great! Personally when I'm using this package I don't really care about seeing the PDF until I'm done for the session and want to share it with someone else (espcially after one becomes confident with the syntax and don't need to constantly check if it exports right), so if it was just a manual pdf generation that would be fine. In any case the pdf generation is too slow to work as a genuinely live update. Happy holidays to you too!

**Comment by superlou** [comment]
Sorry for going silent, and happy holidays to everyone.  In my personal workflow, I don't have a need for auto-update on preview.  I think that it might have been party of the legacy preview purely out of laziness on my part.  The legacy preview was relatively quick (though inaccurate), so it didn't get in the way too much.

I also agree that there likely aren't too may people editing and wanting live updates of their entire script on every save.  In a perfect world, the use case I could see for live update would be if it "knew" what you were working on, either by editor cursor position or a previous selection.

All things considered, I like the idea of removing auto-updating previews on save by default but allowing that to be turned on in a configuration setting.  And of course, solving the bug.

**Comment by jrbostic** [comment]
I agree that it would be cool to have that as an option.  But as I described in my pull request, it's probably got a few more moving parts to have it work correctly than I originally thought. I also started to wonder if it isn't one of those features that would be undervalued for the complexity of implementing it.  My inclination is to tentatively remove it just to fix the bug... And see if anyone actually cares.  I've got about half of the code worked out and I'd be willing to do it if there's an actual demand.

**Comment by superlou** [comment]
Just went through the pull request, and I agree with leaving out auto-update.  I can look into it a bit more too if someone decides they need the auto-update functionality.  I haven't dealt with those hooks in a long time, and the bug definitely seems more important to fix than this feature.

**Comment by jrbostic** [comment]
I'm with you.  And to be fair, your original preview didn't have this problem, I think.  I'm pretty sure this was introduced when I started implicitly delegating to pdf-preview.  The old view could be properly toggled (and was all internally managed), where the new one just writes/opens the file and expects pdf-view to open it.  I just didn't think all the way through this scenario with the persistent callback.

**Comment by jrbostic** [comment]
I think this is closed?

**Comment by superlou** [comment]
I think so.  I wasn't able to reliably recreate the issue before, so I'm not 100% sure it's gone.  I'll close it for now.
