### ISSUE TITLE
Can't give "synopsis" a syntax highlight in the stylesheet. 

### ISSUE THREAD

**Issue by rubensz** [superlou/fountain-atom#50]
I been changing the colors of my fountain syntax highlights but hit a bit of a problem with the "synopsis" as the fountain grammer identify it is "meta.paragraph.text" which is the same as my business. Would like to change the color of the synopsis to be the same as that color of the synopsis text in the Outline View but don't know how to do that now. 
In a future update, could "synopsis" have its own syntax highlight?

P.S
Thanks to everyone that are contributing to this amazing project. It has changed my life and made screenwriting more fun and a lot less hassle. Thank you.

**Comment by superlou** [comment]
@rubensz, can you post a quick fountain snippet to make sure we're thinking about the same thing?

I think I understand what you're saying, though. If memory serves, there was some other plugin I used as a reference when I selected those classes for the synopsis, but I can't pin down a good reason at this point.

**Comment by rubensz** [comment]
@superlou, thanks for responding!
Please excuse this n00b, what is a fountain snippet?

**Comment by superlou** [comment]
No worries.  Just a short piece of a Fountain document that demonstrates the issue.

**Comment by rubensz** [comment]
OK. Embarrassed to admit that I'm not sure how to do that.

The way I changed the color of the syntax highlight is select a element in the screenplay and held down Alt+Cmd+P. The name of the scope was then pasted into this code in the stylesheet. 

`atom-text-editor.editor .syntax--entity.syntax--name.syntax--character.syntax--fountain {
  color: #6187C3;`

When I select the synopsis and press "Alt+Cmd+P", what comes up is "meta.paragraph.text" which is used for scene business (A.K.A "Action" in Final Draft speak) so when I change the color, the synopsis takes on the intended color but so does my business.

Does this make any sense just more confusing?

**Comment by superlou** [comment]
Are you talking specifically about [synopsis lines starting with an =](https://fountain.io/syntax#section-sections)?

**Comment by rubensz** [comment]
Yes, sir!

**Comment by superlou** [comment]
This should be possible in 0.7.2 with as `comment.synopses.fountain`.
