### ISSUE TITLE
Q: How to add custom class for each character dialog lines?

### ISSUE THREAD

**Issue by X-Raym** [superlou/fountain-atom#54]
Hi,

I would love to be able to have dedicated color for each characters names over a dialog line, so I can apply custom style (like colors) to each one of these.

Eg:

```
JOHN
How are you?

JACK
I'm fine, thank you!
```

In this case, I could have JOHN in blue and JACK in orange.

How could I inject characters name into the class?
Do you see a better method for doing what I am looking for ?

Thanks !

**Comment by X-Raym** [comment]
I tried another approach : adding new rules to [Pigments](https://atom.io/packages/pigments).

But this is a failure so far.

**Comment by X-Raym** [comment]
Oh wait, I just succeed by taking the code in https://github.com/abe33/atom-pigments/issues/134#issuecomment-174335530 and adding my own color rules !! Awesome :P

**Comment by superlou** [comment]
@X-Raym, glad you figured it out! Could you give an example of the color rule you used in case someone else is looking to do the same thing? Thanks!

**Comment by X-Raym** [comment]
Ok seems good for performance with my code snippet (I added a scope so that it only track .fountain files).

Code to put in global init.js file:

```coffee
atom.packages.serviceHub.consume 'pigments.api', '1.0.0', (pigmentsAPI) ->
  colorRegexp = "\\b(ZAWN|EURG|KRILG|FRUDE|PLAUDE|BERDE|FLETCHER|NARRATEUR|CHANCELIER|FERGUSON|GAYLORD)\\b(?![-\\.:=\\(])"
  registry = pigmentsAPI.getProject().getColorExpressionsRegistry()

  registry.createExpression 'my-custom-colors', colorRegexp, ['*'], (match, expression, context) ->
    colors =
      ZAWN: "#0000FF"
      EURG: "#9966CC"
      KRILG: "#FF0000"
      FRUDE: "#800000"
      PLAUDE: "#FF8080"
      BERDE: "#23B8DC"
      FLETCHER: "#B3B300"
      NARRATEUR: "#94006B"
      CHANCELIER: "#355e00"
      FERGUSON: "#ff00ff"
      GAYLORD: "#6b4794"

    [_,name] = match


    scopes: ['fountain']

    @colorExpression = @name = name
    @hex = colors[name].replace('#','')
```

Results:

![Demo](https://monosnap.com/file/5a8OeftVPRgiroIJTXf3jOE191buO7.png)

Very handy for groups dialogs!
(note that pigments have other way to display colors)

https://github.com/abe33/atom-pigments#marker-type

There is a manual style to also put on global stylesheet to overcome an actual bug with Pigments:

https://github.com/abe33/atom-pigments/issues/369#issuecomment-373777685

Apart from that, seems to works very nicely so far!
