### ISSUE TITLE
Fr: Resizable and Positionable Outline Preview

### ISSUE THREAD

**Issue by X-Raym** [superlou/fountain-atom#55]
Hi,

Currently, Outline Preview width can't be adjusted via click and drag on a edge.

It would be nice if it could.

Also, being able to set it to the left would be nice,

Thanks for listening !

**Comment by X-Raym** [comment]
I think panel like those created by the MarkDown Preview package are more flexible. They can be click and drag, put elsewhere, resized, etc...

https://github.com/atom/markdown-preview

**Comment by superlou** [comment]
The problem is that back when the package was first written, there was only the [Panel API](https://atom.io/docs/api/v1.25.1/Panel), which [we are using](https://github.com/superlou/fountain-atom/blob/master/lib/fountain-outline-view.coffee#L24) to create the outline preview. I believe we need to update to the [Dock API](https://atom.io/docs/api/v1.25.1/Dock) which gets us all of the benefits of flexible "panels" without having to brute-force the adjustment logic.

**Comment by jrbostic** [comment]
It would probably also require some rework of the panel's tab header.  All of that icon stuff is sort of being arranged in there manually.  I think it's a bit of a hack, so hopefully a newer API has a standard way of doing something like that.

**Comment by X-Raym** [comment]
As far as I understand, Dock API is supposed to be simpler to manage in the long run, than having to add new functions to a Panel:

http://blog.atom.io/2017/05/16/atom-1-17.html

>Docks provide a high-level API that makes it simpler for package authors to implement this kind of easy-to-toggle panel and give users a lot more control over how their panels are arranged. Just like panes in the center of the Atom workspace, panes within docks can be split and resized in arbitrary ways, and since dock panes can contain multiple tabbed items, it’s now possible for tool panels written by different package authors to coherently share screen real estate at the periphery of the workspace.

Seems like it would be a good move for this plugin :)

Thanks again for considering this !

**Comment by superlou** [comment]
I've had a little bit of luck actually creating a dock, which was trickier than I thought it would be. I'm looking into what it would take to port the existing view. @jrbostic, do you remember where @list in fountain-outline-view.coffee is initialized? I see `.empty` being called on it, but no creation.

**Comment by jrbostic** [comment]
Of the top of my head, I think the main module file kicks off the process and then there's the main initialization function for the outline view.  After that it runs in a loop on save or change.  I would think it's either on the view's scope directly or in the panel initialization.  If not there, somewhere early in the loop that runs to populate data.  One thing that I also remember is there's lists.  One is the initial data structure with all the info, the second is where it builds the actual HTML (though technically a string).

**Comment by superlou** [comment]
Check out #58 and let me know if anything isn't behaving. It should be 95% of the way there: just a really annoying edge-case I'm not sure how to handle in serialization.

**Comment by jrbostic** [comment]
Work completed with PR-58.

**Comment by X-Raym** [comment]
Cool thanks for the hard work !
