### ISSUE TITLE
PDF Export/Print to Pdf

### ISSUE THREAD

**Issue by demented-turtle** [superlou/fountain-atom#6]
If you could add PDF export that would really streamline the fountain workflow on Linux. 
There is a pretty great web app already (MIT License) for this called [Afterwriting](https://github.com/ifrost/afterwriting-labs) which you may be able pull from.

**Comment by superlou** [comment]
@demented-turtle, I think I can do it using [markdown-pdf](https://www.npmjs.com/package/html-pdf).   I had originally tried doing PDF export a long while back and had run into some issue with Atom that make it unexpectedly difficult, and had started creating [my own webapp](http://louissimons.com/scriptjr/) to get around it.  I'll give it a shot now that Atom is more mature.

Do you need 100% accurate script formatting with exact margins, page numbers, etc., or would converting the preview view to a PDF be sufficient?

**Comment by ichiragvadgama** [comment]
@superlou While preview view PDF is nice, 100% accurate script formatting would be a most ideal as it would be a complete solution for end result deliverable!

**Comment by superlou** [comment]
Sorry this is taking so long.  I'm not sure when/if I'm going to get a chance to implement this, but if anyone is able to submit a pull-request with these features, I'll happily merge them.

**Comment by superlou** [comment]
@captaindooley What are you using to generate your PDFs?  It's something we've been looking to integrate into this plugin for a while.

**Comment by jrbostic** [comment]
Are you currently working on this?  If not, I think I may know a way...

**Comment by superlou** [comment]
@jrbostic My hope was to clean-up the quality of the generated HTML preview, and then "print" that to PDF so that we wouldn't have to maintain yet another text-to-Fountain tool on top of the syntax highlighter and the HTML builder.  There are a lot of nitpicks with the current preview styling that make it not quite the proper formatting, e.g. margins.  That said, I'm not too opinionated on it so long as it doesn't require an internet connection to work.

I'm not actively working on it, and it's really the only thing that makes me feel like we don't have the features to call this a "1.0.0" package.  Anything you can do would be appreciated.

**Comment by jrbostic** [comment]
@superlou I got the basics of this working today.  Filling out a few unit tests now.  It does use the afterwriting CLI tool.  MIT License.  Hope that's not an issue?  No network access.  There's more but I'll save it for the pull request.

**Comment by jrbostic** [comment]
@superlou @demented-turtle Pull Request #23

**Comment by superlou** [comment]
Basics (and more) thanks to @jrbostic.  We'll tackle specific issues in new issues.  Thanks!

**Comment by captaindooley** [comment]
I know this is closed, but I just attempted to use this and realized it puts "Format: Screenplay" at the top of the first page of the actual script (after the title page). Is that something that can be fixed?

**Comment by jrbostic** [comment]
@captaindooley   I haven't seen this and was not able to reproduce.  To assist in identifying the issue, it would be helpful to create a new issue with some information about how you produced it.  A screenshot of the output and the exact text that came before and after the unwanted text?

**Comment by captaindooley** [comment]
Sure. Sorry - I'll do that.
