### ISSUE TITLE
Using the dot to set a scene heading makes the dot appear in the outliner

### ISSUE THREAD

**Issue by Tilix4** [superlou/fountain-atom#63]
Hi !
Thank you for this wonderful package !

I'm sure you already know that, but it could be great that le dot I use to set a scene heading doesn't appear in the outliner. 
I think it's a small fix.

**Comment by superlou** [comment]
Sorry this is taking so long. I'm trying to merge the updates to the new dock API before tackling this.

**Comment by Tilix4** [comment]
No problem, I was about looking at it.
It works for me. Do you commit it or you want me to do it ?

**Comment by superlou** [comment]
As soon as the new dock stuff is pulled in, I'll add in this fix. Should happen either tonight or tomorrow.

**Comment by superlou** [comment]
You should be able to try this in master, but we're still trying to get the dock API changes in before we cut the next release.
