### ISSUE TITLE
Feedback: Setting Atom for Fountain Editing

### ISSUE THREAD

**Issue by X-Raym** [superlou/fountain-atom#65]
Hi,

Not a issue or a feature request,
I just wanted to show you how I use Atom (with this Fountain plugin) to write scripts (the other package I have installed, the custom codes I made, the workaround I found for some non-optimized features implementation - like the current outline view which can't be resized, the outline view which only works on current active file (https://github.com/superlou/fountain-atom/issues/57) etc) and other reports I opened there).

(Note: @superlou I don't want to spam your issue board with that, but I have no way to contact you privately. I hope that you are ok for me contacting you this way. Don't hesitate to delete the post if you think it does not belong here).

Showcasing Fountain related work in Atom outside of this package can give you detailed feedback about how your package is used, inspire you to implement some feature, or just help other fountain-atom editor who want to extend the screenwriting related features possibilities of Atom.

I show all that in the article: [Screenwritng in Fountain Format: Using and Customizing Atom Editor](https://www.extremraym.com/en/fountain-screenwriting-atom/).

All these Fountain editing capabilities have been brought thanks to your plugin, so again thanks you very much for it !

Cheers !

**Comment by superlou** [comment]
Hello, @X-Raym. I appreciate the kind words, and by all means, the work on this package has come from multiple developers, not just myself. I'm glad that we're fulfilling a need.

The feedback and feature requests are very useful. If the features you need are tracked with other issues (#55, #56, #57), I'm going to close this issue for now. Maybe we can add a link to your articles as they progress to the Readme or wiki?

**Comment by X-Raym** [comment]
Indeed, I opened dedicated issues for all my FR, so that it is easier to track. Thanks again for taking the time to work on it !

> Maybe we can add a link to your articles

Sure, it will be nice!
