### ISSUE TITLE
Deprecated selector in `fountain/styles/fountain.less`

### ISSUE THREAD

**Issue by Tolmark12** [superlou/fountain-atom#7]
In `fountain/styles/fountain.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .fountain.scene` => `atom-text-editor.editor .syntax--fountain.syntax--scene`

* `atom-text-editor::shadow .fountain.character` => `atom-text-editor.editor .syntax--fountain.syntax--character`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by morekitsch** [comment]
Updated the styles and tested seems to be good. New version updated v5.0.1

**Comment by superlou** [comment]
@morekitsch, did you push the APM update out or is that something only I can do?

**Comment by morekitsch** [comment]
I junk it's a you thing. That or I simply didn't know that was a thing :)
first time doing an update.

**Comment by superlou** [comment]
It should be pushed as 0.5.1.  Let me know if it's not updating properly.

**Comment by Tolmark12** [comment]
@superlou, @morekitsch Thank you!
