### ISSUE TITLE
Spaces/Tabs Not Recognized in Action Lines for PDF Preview/Export

### ISSUE THREAD

**Issue by eWrekt** [superlou/fountain-atom#70]
Hey folks,

In fountain, I can start an action with spaces and tabs that should carry over into the interpreted document; however, the current PDF preview and export in Atom does not include this feature. Is it possible to support this?

Quote from [fountain.io:](https://fountain.io/syntax#section-action):

> Tabs and spaces are retained in Action elements, allowing writers to indent a line. Tabs are converted to four spaces.

I use this writing technique in quite a few screenplays so exporting directly from Atom with it included would be awesome.

Thank you!

source:  [https://fountain.io/syntax#section-action](https://fountain.io/syntax#section-action)

**Comment by jrbostic** [comment]
I'm going to guess that this is something to be logged in the afterwriting dependency repo.  There may have been some technical reason why... But we'd probably have to inquire with the author.

**Comment by eWrekt** [comment]
I'll go and post over there then. Thanks!
