### ISSUE TITLE
no outline in atom 1.24.0 on win 7 with fountain-atom 0.8.0

### ISSUE THREAD

**Issue by froh** [superlou/fountain-atom#75]
Hi,

I installed fountain using the atom package installer in a fresh install of atom on win 7.

I then for testing purposes downloaded some .fountain scripts.

no outline for none of them.

**Comment by superlou** [comment]
Did any errors appear when you installed the package or when you tried to open the outline? Did you try to open the outline using the shortcut or from the command palette?

**Comment by froh** [comment]
fascinating.  ctrl-alt-o works.

I had only tried the "Packages->Fountain->Open Outline View".

even more fascinating:  when the outline was activated once using ctrl-alt-o, it will also toggle using the Menu.

**Comment by froh** [comment]
I also updated to the new atom 0.29.0 now, and I did a few experiments, restarting atom again and again.

So I need to update my description:

when I activate the outline view, the editor pops into that view and the outline shows blank, _no matter how I've activated it_ (keyboard or mouse).

as soon as I switch back into the .fountain, the outline is rendered, _no matter how I switch_.

so:

1. start atom
2. open .fountain file (or have it open from previous session)
3. ctrl-alt-o -> see nothing
4. ctrl-k ctrl-left -> tada! outline shows!

and from there on the outline works as expected (turn off/back on again, renders immediately)

**Comment by superlou** [comment]
That sounds like normal behavior. If I understand right, the outline pops up, it just has no items in it? Is that what you are describing by step 3?

Due to how the outline currently tries to figure out the active editor, you have to click your fountain file once before the outline is populated.

**Comment by superlou** [comment]
If I'm accurately understanding the issue, let's tackle this in #78. Otherwise, feel free to reopen.
