### ISSUE TITLE
Sections and Synopsis show up in PDF

### ISSUE THREAD

**Issue by squinonescolon** [superlou/fountain-atom#86]
When I preview or export PDF with the latest 0.8.1, the sections (#) and Synopsis(=) show up in the PDF. If I try the same text on Afterwriting online or the downloaded version I don't get the same problem.

**Comment by jrbostic** [comment]
Check your package settings.  Those are probably defaults.

**Comment by jrbostic** [comment]
That does bring up the issue, maybe we should be writing a local config file on the host machine to retain settings across releases?  If that's the issue here.

**Comment by squinonescolon** [comment]
This is a new installation, never used Atom before, but I’ll check to see if there’s a setting somewhere. 

Steven Quiñones Colón
VFX Producer
939.240.1006

**Comment by squinonescolon** [comment]
You can close this. Thanks
