### ISSUE TITLE
Install Issue?

### ISSUE THREAD

**Issue by theblackholebytes** [superlou/fountain-atom#97]
It says: `Installing “fountain@0.8.3” failed.`
Under more detail: 
`Failed to install fountain because Git was not found.
The fountain package has module dependencies that cannot be installed without Git.
You need to install Git and add it to your path environment variable in order to install this package.
You can install Git by downloading, installing, and launching GitHub for Windows: https://windows.github.com
Run apm -v after installing Git to see what version has been detected.`
GitHub is installed and working. I'm confused on what else I need to do.

**Comment by superlou** [comment]
Did you try to install through the Atom GUI or the Atom command line? What version of Atom are you running, and what is your OS? In a command prompt, if you type `git` and press enter, what do you get?

**Comment by emmanuelmenon** [comment]
I just had this issue today. I fixed it by running Atom as an admin, and then installing the package.

**Comment by theblackholebytes** [comment]
> Did you try to install through the Atom GUI or the Atom command line? What version of Atom are you running, and what is your OS? In a command prompt, if you type `git` and press enter, what do you get?

Thank you for getting back to me.
I tried through the GUI. I'm running Atom 1.45.0 on Windows 10. 
On the command prompt: `'git' is not recognized as an internal or external command, operable program or batch file.`
So I guess that's my problem.

> I just had this issue today. I fixed it by running Atom as an admin, and then installing the package.

Thank you for suggesting this but, sadly, it didn't work.

**Comment by superlou** [comment]
When you installed Github Desktop for Windows, did it give you an option to add "git" to your path? Can you try reinstalling Github Desktop as admin? It sounds like Windows doesn't know where to find git.

**Comment by Lukas2019** [comment]
Same Issue hire with divergent windows 10 PCs (tested in different Networks) Both have git hub Desktop installed.
Die Installation was tried withe the UI.
On one of them I Installed pure git as well but dit not work ether... even wen executed as admin it did not work.
On Arch Linux I had no problem.... 
If you need more Information pleas let me know I would be happy to provide them because I love what you wrote.

**Comment by superlou** [comment]
Please enter `git` in a command prompt and paste the output.

**Comment by Lukas2019** [comment]
Pleas give me a moment I need to find the Power suply for the Windows Laptop...

**Comment by Lukas2019** [comment]
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]                                                                    [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]                                                         [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]                                                     [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]                                                            <command> [<args>]                                                                                                                                                                                                                   These are common Git commands used in various situations:                                                                                                                                                                                       start a working area (see also: git help tutorial)                                                                         clone             Clone a repository into a new directory                                                               init              Create an empty Git repository or reinitialize an existing one                                                                                                                                                             work on the current change (see also: git help everyday)                                                                   add               Add file contents to the index                                                                        mv                Move or rename a file, a directory, or a symlink                                                      restore           Restore working tree files                                                                            rm                Remove files from the working tree and from the index                                                 sparse-checkout   Initialize and modify the sparse-checkout                                                                                                                                                                                  examine the history and state (see also: git help revisions)                                                               bisect            Use binary search to find the commit that introduced a bug                                            diff              Show changes between commits, commit and working tree, etc                                            grep              Print lines matching a pattern                                                                        log               Show commit logs                                                                                      show              Show various types of objects                                                                         status            Show the working tree status                                                                                                                                                                                               grow, mark and tweak your common history                                                                                   branch            List, create, or delete branches                                                                      commit            Record changes to the repository                                                                      merge             Join two or more development histories together                                                       rebase            Reapply commits on top of another base tip                                                            reset             Reset current HEAD to the specified state                                                             switch            Switch branches                                                                                       tag               Create, list, delete or verify a tag object signed with GPG                                                                                                                                                                collaborate (see also: git help workflows)                                                                                 fetch             Download objects and refs from another repository                                                     pull              Fetch from and integrate with another repository or a local branch                                    push              Update remote refs along with associated objects                                                                                                                                                                           'git help -a' and 'git help -g' list available subcommands and some                                                     concept guides. See 'git help <command>' or 'git help <concept>'                                                        to read about a specific subcommand or concept.                                                                         See 'git help git' for an overview of the system.

**Comment by Lukas2019** [comment]
```
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone             Clone a repository into a new directory
   init              Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add               Add file contents to the index
   mv                Move or rename a file, a directory, or a symlink
   restore           Restore working tree files
   rm                Remove files from the working tree and from the index
   sparse-checkout   Initialize and modify the sparse-checkout

examine the history and state (see also: git help revisions)
   bisect            Use binary search to find the commit that introduced a bug
   diff              Show changes between commits, commit and working tree, etc
   grep              Print lines matching a pattern
   log               Show commit logs
   show              Show various types of objects
   status            Show the working tree status

grow, mark and tweak your common history
   branch            List, create, or delete branches
   commit            Record changes to the repository
   merge             Join two or more development histories together
   rebase            Reapply commits on top of another base tip
   reset             Reset current HEAD to the specified state
   switch            Switch branches
   tag               Create, list, delete or verify a tag object signed with GPG

collaborate (see also: git help workflows)
   fetch             Download objects and refs from another repository
   pull              Fetch from and integrate with another repository or a local branch
   push              Update remote refs along with associated objects

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
See 'git help git' for an overview of the system.

```

**Comment by Lukas2019** [comment]
( is it right?)

**Comment by Lukas2019** [comment]
It look like it was installt but then dis Errow appiered :
```
Unexpected token } in JSON at position 1970 in C:\Users\Cathlin\.atom\packages\fountain\package.json
Hide Stack Trace
SyntaxError: Unexpected token } in JSON at position 1970
    at JSON.parse (<anonymous>)
    at m (C:\Users\Cathlin\AppData\Local\atom\app-1.46.0\resources\app\static\<embedded>:11:579975)
    at c (C:\Users\Cathlin\AppData\Local\atom\app-1.46.0\resources\app\static\<embedded>:11:580270)
    at Object.readFileSync (C:\Users\Cathlin\AppData\Local\atom\app-1.46.0\resources\app\static\<embedded>:11:581363)
    at PackageManager.loadPackageMetadata (C:\Users\Cathlin\AppData\Local\atom\app-1.46.0\resources\app\static\<embedded>:11:385580)
    at PackageManager.loadAvailablePackage (C:\Users\Cathlin\AppData\Local\atom\app-1.46.0\resources\app\static\<embedded>:11:380493)
    at config.transact (C:\Users\Cathlin\AppData\Local\atom\app-1.46.0\resources\app\static\<embedded>:11:379697)
    at Config.transact (C:\Users\Cathlin\AppData\Local\atom\app-1.46.0\resources\app\static\<embedded>:11:331762)
    at PackageManager.loadPackages (C:\Users\Cathlin\AppData\Local\atom\app-1.46.0\resources\app\static\<embedded>:11:379635)
    at t.loadState.then (C:\Users\Cathlin\AppData\Local\atom\app-1.46.0\resources\app\static\<embedded>:1:742323)
  at C:\Users\Cathlin\.atom\packages\fountain\package.json:1:1
```

**Comment by superlou** [comment]
Hmm, that actually looks fine for `git`. I was kind of hoping it was something simple like the executable wasn't in the path.

**Comment by Lukas2019** [comment]
Ok is the errow  message saying any thing?

**Comment by Lukas2019** [comment]
so after Installing git from  [https://git-scm.com/download/win](https://git-scm.com/download/win) and a reboot it looks like it was installed but it diosn't work

**Comment by Lukas2019** [comment]
Jep it works now!!! THX for your time and the program

**Comment by superlou** [comment]
I'm glad it's working! Any idea what you changed?

**Comment by Lukas2019** [comment]
No. not at all.

**Comment by superlou** [comment]
Either way, happy it's working. Sometimes that's just how it is.
