### ISSUE TITLE
Running package spec test on a new unedited fork throws up errors

### ISSUE THREAD

**Issue by emmanuelmenon** [superlou/fountain-atom#99]
### Failures
**Fountain Outline View Spec - formatting - it should find expected scenes**
```
Error: Expected [ { line : 12, title : 'EXT. BRICK'S PATIO - DAY
', type : 'scene', hasNote : false, depth : 0, parentEndline : 161, endline : 52 }, { line : 52, title : 'INT. TRAILER HOME - DAY
', type : 'scene', hasNote : false, depth : 0, parentEndline : 161, endline : 69 }, { line : 69, title : 'EXT. BRICK'S POOL - DAY
', type : 'scene', hasNote : false, depth : 0, parentEndline : 161, endline : 80 }, { line : 80, title : 'SNIPER SCOPE POV
', type : 'scene', hasNote : false, depth : 0, parentEndline : 161, endline : 95 }, { line : 95, title : 'OPENING TITLES
', type : 'scene', hasNote : false, depth : 0, parentEndline : 161, endline : 105 }, { line : 105, title : 'EXT. WOODEN SHACK - DAY
', type : 'scene', hasNote : false, depth : 0, parentEndline : 161, endline : 129 }, { line : 129, title : 'INT. GARAGE - DAY
', type : 'scene', hasNote : false, depth : 0, parentEndline : 161, endline : 144 }, { line : 144, title : 'EXT. PALATIAL MANSION - DAY
', type : 'scene', hasNote : false, depth : 0, parentEndline : 161, endline : 161 } ] to equal [ { line : 12, title : 'EXT. BRICK'S PATIO - DAY', type : 'scene', hasNote : false, depth : 0, parentEndline : 161, endline : 52 }, { line : 52, title : 'INT. TRAILER HOME - DAY', type : 'scene', hasNote : false, depth : 0, parentEndline : 161, endline : 69 }, { line : 69, title : 'EXT. BRICK'S POOL - DAY', type : 'scene', hasNote : false, depth : 0, parentEndline : 161, endline : 80 }, { line : 80, title : 'SNIPER SCOPE POV', type : 'scene', hasNote : false, depth : 0, parentEndline : 161, endline : 95 }, { line : 95, title : 'OPENING TITLES', type : 'scene', hasNote : false, depth : 0, parentEndline : 161, endline : 105 }, { line : 105, title : 'EXT. WOODEN SHACK - DAY', type : 'scene', hasNote : false, depth : 0, parentEndline : 161, endline : 129 }, { line : 129, title : 'INT. GARAGE - DAY', type : 'scene', hasNote : false, depth : 0, parentEndline : 161, endline : 144 }, { line : 144, title : 'EXT. PALATIAL MANSION - DAY', type : 'scene', hasNote : false, depth : 0, parentEndline : 161, endline : 161 } ].
at fountain-outline-view-spec.coffee:40:42
```

**Fountain Outline View Spec - formatting with page breaks - it should not include page break "==="** (seems similar to - https://github.com/superlou/fountain-atom/issues/93)
```
Error: Expected 3 to equal 2
at fountain-outline-view-spec.coffee:188:40
```
```
Error: Expected 'INT. CAR WASH
' to equal 'INT. CAR WASH'.
at fountain-outline-view-spec.coffee:190:42
```

**Fountain PDF Converter Spec - conversion paths - it should be able to overwrite existing pdf**
```
Error: Expected function to throw an exception
at fountain-pdf-converter-spec.coffee:139:48
```

### Steps to reproduce
1. Forked repo
2. Cloned repo
3. Ran `apm install`
4. Opened atom using `atom -d .`
5. Hit `ctrl-shift-y`

The formatting of the errors is exactly as they were when I copied them from the spec suite. 

Also, offtopic, but I just wanna say that I love this package and I don't think I could go back to writing any other way, so thank you for developing it and maintaining it!

**Comment by emmanuelmenon** [comment]
>What version Atom are you running?
- **Atom Version:** 1.45.0

>Also, if you run the specs multiple times, do your errors change?
- The errors do not change.

>On the second error, what OS and Atom version are you running?
- **OS:** Windows 10 Home - Insider Preview (OS Build: 19603.1000)
- **Atom Version:** 1.45.0

**Comment by superlou** [comment]
For better or worse, I just tried the trunk in Atom 1.45.0 x64 on both Linux Mint 19.3 and Windows 10 "Enterprise Evaluation" (build 18363.778 in a VM) and all the tests passed. I guess it's possible there's something funny in the later build, but I kind of doubt it.

I just realized, though, when I set up Git for Windows, I configured it to check out line endings as is and commit Unix style. I think the default on Windows might be to checkout, silently convert to windows style line endings, then silently convert back to Unix style for commit. If it's not a huge hassle, could you try uninstalling the Fountain plugin, changing your Git for Windows settings to check-out Unix style, then reinstall and run the tests again?

**Comment by emmanuelmenon** [comment]
Yep! You were right. For anybody who comes across this issue in the future, the command to change your check-out settings is `git config --global core.autocrlf false`. Thanks for the help!
